arch: vit_small_16   # vit_small_16 | vit_base_16
image_size: 224
patch_size: 16
embed_dim: 384
num_heads: 6
depth: 8

ema_momentum: [0.996, 0.996]   # [start, end]; set end > start for linear warmup to 1.0
remove_head: true